package com.fastfoot.bets.model;

public enum TipoProbabilidadeResultadoPartida {
	ESTATISTICAS_FINALIZACAO,
	SIMULAR_PARTIDA,
	ESTATISTICAS_FINALIZACAO_DEFESA,
	ESTATISTICAS_FINALIZACAO_POISSON,
	SIMULAR_PARTIDA_HABILIDADE_GRUPO,
}
