package com.fastfoot.bets.model;

public enum TipoProbabilidadeResultadoPartida {
	ZERO,
	SIMULAR_PARTIDA,//1
	ESTATISTICAS_FINALIZACAO,//2
	ESTATISTICAS_FINALIZACAO_DEFESA,//3
	ESTATISTICAS_FINALIZACAO_POISSON,//4
	SIMULAR_PARTIDA_HABILIDADE_GRUPO,//5
}
