package com.fastfoot.financial.model;

public enum TipoMovimentacaoFinanceira {

	ENTRADA_PATROCINIO,//0
	ENTRADA_SOCIO_TORCEDOR,//1 //TODO
	ENTRADA_INGRESSOS,	//2
	ENTRADA_PREMIACAO,//3
	ENTRADA_DIREITOS_TRANSMISSAO,//4 //TODO
	ENTRADA_VENDA_JOGADOR,//5
	
	SAIDA_SALARIO_JOGADOR,//6
	SAIDA_MANUTENCAO_ESTADIO,//7 //TODO
	SAIDA_TREINAMENTO_ESPECIFICO,//8 //TODO
	SAIDA_SALARIO_EQUIPE_TECNICA,//9 //TODO
	SAIDA_OLHEIRO,//10 //TODO
	SAIDA_COMPRA_JOGADOR,//11
	
	CAIXA_INICIAL,//12
	
	SAIDA_JUROS_BANCARIOS,//13
	
	CAIXA_INICIO_TEMPORADA,//14
	CAIXA_FIM_TEMPORADA,//15
	CAIXA_VARIACAO_TEMPORADA,//16
	
	SAIDA_PREMIACAO_JOGADORES,//17
	
	ENTRADA_INGRESSOS_AMISTOSOS,	//18
	
	ATIVO_VALOR_ELENCO, //19
	;

}
