package com.fastfoot.financial.model;

public enum TipoMovimentacaoFinanceira {

	ENTRADA_PATROCINIO,
	ENTRADA_SOCIO_TORCEDOR,
	ENTRADA_INGRESSOS,	
	ENTRADA_PREMIACAO,
	ENTRADA_DIREITOS_TRANSMISSAO,
	ENTRADA_VENDA_JOGADOR,
	SAIDA_SALARIO_JOGADOR,
	SAIDA_MANUTENCAO_ESTADIO,
	SAIDA_TREINAMENTO_ESPECIFICO,
	SAIDA_SALARIO_EQUIPE_TECNICA,
	SAIDA_OLHEIRO,
	SAIDA_COMPRA_JOGADOR,
	CAIXA_INICIAL
	;

}
