package com.fastfoot.model;

public class ParametroConstantes {

	/*public static final String JOGAR_CONTINENTAL_III = "JOGAR_CONTINENTAL_III";*/
	
	public static final String JOGAR_COPA_NACIONAL_II = "JOGAR_COPA_NACIONAL_II";
	
	public static final String JOGAR_5_LIGAS = "JOGAR_5_LIGAS";
	
	public static final String MARCAR_AMISTOSOS_AUTOMATICAMENTE = "MARCAR_AMISTOSOS_AUTOMATICAMENTE";

	public static final String NUMERO_CAMPEONATOS_CONTINENTAIS = "NUMERO_CAMPEONATOS_CONTINENTAIS";

	public static final String ESTRATEGIA_COPA_NACIONAL = "ESTRATEGIA_COPA_NACIONAL";//AUTOMATICA, 8, 12, 16//TODO
	
	public static final String ESTRATEGIA_PROMOTOR_CONTINENTAL = "ESTRATEGIA_PROMOTOR_CONTINENTAL";//DOIS_MELHORES, OUTRO_CAMPEONATO

	public static final String ESTRATEGIA_PROMOTOR_COPA_NACIONAL = "ESTRATEGIA_PROMOTOR_COPA_NACIONAL";//AUTOMATICO, OITO_CLUBES, DOZE_CLUBES, DEZESSEIS_CLUBES 
}
