package com.fastfoot.model;

public class ParametroConstantes {

	//2, 3
	public static final String NUMERO_CAMPEONATOS_CONTINENTAIS = "NUMERO_CAMPEONATOS_CONTINENTAIS";

	//SEGUNDO_MELHOR_GRUPO, MELHOR_ELIMINADO_CAMPEONATO_SUPERIOR
	public static final String ESTRATEGIA_PROMOTOR_CONTINENTAL = "ESTRATEGIA_PROMOTOR_CONTINENTAL";

	public static final String ESTRATEGIA_PROMOTOR_CONTINENTAL_PARAM_SEG = "SEGUNDO_MELHOR_GRUPO";

	public static final String ESTRATEGIA_PROMOTOR_CONTINENTAL_PARAM_ELI = "MELHOR_ELIMINADO_CAMPEONATO_SUPERIOR";

	//true, false
	public static final String JOGAR_COPA_NACIONAL_II = "JOGAR_COPA_NACIONAL_II";

	//4 (16 TIMES), 5 (20 a 24 TIMES), 6 (28 a 32 TIMES)
	public static final String NUMERO_RODADAS_COPA_NACIONAL = "NUMERO_RODADAS_COPA_NACIONAL";

	public static final String NUMERO_RODADAS_COPA_NACIONAL_PARAM_4R = "4 (16 TIMES)";

	public static final String NUMERO_RODADAS_COPA_NACIONAL_PARAM_6R = "6 (28 a 32 TIMES)";

	public static final String NUMERO_RODADAS_COPA_NACIONAL_PARAM_5R = "5 (20 a 24 TIMES)";

	//true, false
	public static final String MARCAR_AMISTOSOS_AUTOMATICAMENTE = "MARCAR_AMISTOSOS_AUTOMATICAMENTE";

}
