package com.fastfoot.match.model;

public enum JogadorApoioCriacao {
	LATERAL_DIREITO_PELO_LADO,
	LATERAL_DIREITO_PELO_MEIO,
	LATERAL_ESQUERDO_PELO_LADO, 
	LATERAL_ESQUERDO_PELO_MEIO,
	VOLANTE_DIREITO_PELO_LADO, 
	VOLANTE_DIREITO_PELO_MEIO,
	VOLANTE_ESQUERDO_PELO_LADO, 
	VOLANTE_ESQUERDO_PELO_MEIO,
	;
}
