package com.fastfoot.probability.model;

public enum TipoCampeonatoClubeProbabilidade {
	ZERO,
	SIMULAR_PARTIDA,//1
	SIMULAR_PARTIDA_ESTATISTICAS_FINALIZACAO,//2
	SIMULAR_PARTIDA_ESTATISTICAS_FINALIZACAO_DEFESA,//3
	SIMULAR_PARTIDA_ESTATISTICAS_FINALIZACAO_POISSON,//4
	SIMULAR_PARTIDA_HABILIDADE_GRUPO,//5
	ESTATISTICAS_SIMPLES,//6
	FORCA_GERAL,//7
	;
}
