package com.fastfoot.probability.model;

public enum TipoClubeProbabilidade {
	ESTATISTICAS_SIMPLES,//0
	ESTATISTICAS_FINALIZACAO,//1
	SIMULAR_PARTIDA,//2
	SIMULAR_PARTIDA_EST_FINALIZACAO,//3
	SIMULAR_PARTIDA_EST_FIN_DEFESA,//4
	SIMULAR_PARTIDA_EST_FINALIZACAO_POISSON,//5
	;
}
