package com.fastfoot.probability.model;

public enum TipoClubeProbabilidade {
	ESTATISTICAS_SIMPLES,
	ESTATISTICAS_FINALIZACAO,
	SIMULAR_PARTIDA,
	SIMULAR_PARTIDA_EST_FINALIZACAO,
	SIMULAR_PARTIDA_EST_DEFESA
	;
}
